### ISSUE TITLE
can't find symbol

### ISSUE THREAD

**Issue by zhanguangao** [react-native-component/react-native-smart-barcode#1]
MainActivity.java:35: error: can't find symbol
            application.setReactNativeHost(new ReactNativeHost(application) {
                       ^
  symbol:  setReactNativeHost(<new ReactNativeHost>)
  position: MainApplication application

**Comment by cyqresig** [comment]
Have you followed the readme and changed the code in MainApplication.java?

**Comment by zhanguangao** [comment]
@cyqresig I forgot to copy  getReactNativeHost() in MainApplication, I added it and now run successful,thanks a lot;

**Comment by zhanguangao** [comment]
@cyqresig I forgot to copy setReactNativeHost() in MainApplication, I added it and now run successful,thanks a lot;
