### ISSUE TITLE
扫描框有时会出现在左上角，返回再次进入又好了

### ISSUE THREAD

**Issue by ryuuc** [react-native-component/react-native-smart-barcode#29]
![qr](https://user-images.githubusercontent.com/24676778/40031995-c77607ae-5824-11e8-9ae8-d3eb9c1d10b1.png)

**Comment by zChaoFan** [comment]
我也出现了这个问题,请问解决了吗

**Comment by ryuuc** [comment]
解决了，扫描界面里加了个shouldComponentUpdate，每次进入时都返回true重新加载了一次，就好了
