### ISSUE TITLE
InteractionManager.runAfterInteractions 不运行

### ISSUE THREAD

**Issue by sundou** [react-native-component/react-native-smart-barcode#8]
退出扫描页后。InteractionManager.runAfterInteractions 方法就失效了。
"react-native": "0.43.4"

**Comment by mjylfz** [comment]
我也遇到这个问题，怎么解决

**Comment by nongh4704** [comment]
因为里面有个动画一直在运行，要改源码，退出界面的时候把动画清除就可以了
